[2023-11-01T13:01:59.050+0700] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline.wait_for_first_dag scheduled__2023-11-01T05:50:00+00:00 [queued]>
[2023-11-01T13:01:59.056+0700] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline.wait_for_first_dag scheduled__2023-11-01T05:50:00+00:00 [queued]>
[2023-11-01T13:01:59.056+0700] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2023-11-01T13:01:59.063+0700] {taskinstance.py:1380} INFO - Executing <Task(ExternalTaskSensor): wait_for_first_dag> on 2023-11-01 05:50:00+00:00
[2023-11-01T13:01:59.077+0700] {standard_task_runner.py:57} INFO - Started process 104 to run task
[2023-11-01T13:01:59.082+0700] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'etl_pipeline', 'wait_for_first_dag', 'scheduled__2023-11-01T05:50:00+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmp892mtlts']
[2023-11-01T13:01:59.085+0700] {standard_task_runner.py:85} INFO - Job 15: Subtask wait_for_first_dag
[2023-11-01T13:01:59.152+0700] {task_command.py:415} INFO - Running <TaskInstance: etl_pipeline.wait_for_first_dag scheduled__2023-11-01T05:50:00+00:00 [running]> on host 0b9baf17cefc
[2023-11-01T13:01:59.234+0700] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='***@example.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_pipeline' AIRFLOW_CTX_TASK_ID='wait_for_first_dag' AIRFLOW_CTX_EXECUTION_DATE='2023-11-01T05:50:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-01T05:50:00+00:00'
[2023-11-01T13:01:59.266+0700] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/sensors/external_task.py", line 334, in execute
    super().execute(context)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/sensors/base.py", line 257, in execute
    raise e
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/sensors/base.py", line 239, in execute
    poke_return = self.poke(context)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 77, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/sensors/external_task.py", line 241, in poke
    serialized_dttm_filter = ",".join(dt.isoformat() for dt in dttm_filter)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/sensors/external_task.py", line 241, in <genexpr>
    serialized_dttm_filter = ",".join(dt.isoformat() for dt in dttm_filter)
AttributeError: 'NoneType' object has no attribute 'isoformat'
[2023-11-01T13:01:59.278+0700] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=etl_pipeline, task_id=wait_for_first_dag, execution_date=20231101T055000, start_date=20231101T060159, end_date=20231101T060159
[2023-11-01T13:01:59.287+0700] {standard_task_runner.py:104} ERROR - Failed to execute job 15 for task wait_for_first_dag ('NoneType' object has no attribute 'isoformat'; 104)
[2023-11-01T13:01:59.337+0700] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-01T13:01:59.367+0700] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
