[2023-11-01T13:19:16.027+0700] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline.wait_for_first_dag scheduled__2023-11-01T06:00:00+00:00 [queued]>
[2023-11-01T13:19:16.036+0700] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline.wait_for_first_dag scheduled__2023-11-01T06:00:00+00:00 [queued]>
[2023-11-01T13:19:16.036+0700] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2023-11-01T13:19:16.054+0700] {taskinstance.py:1380} INFO - Executing <Task(ExternalTaskSensor): wait_for_first_dag> on 2023-11-01 06:00:00+00:00
[2023-11-01T13:19:16.091+0700] {standard_task_runner.py:57} INFO - Started process 255 to run task
[2023-11-01T13:19:16.096+0700] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'etl_pipeline', 'wait_for_first_dag', 'scheduled__2023-11-01T06:00:00+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmpb3fhmrp3']
[2023-11-01T13:19:16.102+0700] {standard_task_runner.py:85} INFO - Job 24: Subtask wait_for_first_dag
[2023-11-01T13:19:16.165+0700] {task_command.py:415} INFO - Running <TaskInstance: etl_pipeline.wait_for_first_dag scheduled__2023-11-01T06:00:00+00:00 [running]> on host 26dc1404ecde
[2023-11-01T13:19:16.257+0700] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='***@example.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_pipeline' AIRFLOW_CTX_TASK_ID='wait_for_first_dag' AIRFLOW_CTX_EXECUTION_DATE='2023-11-01T06:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-01T06:00:00+00:00'
[2023-11-01T13:19:16.304+0700] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/sensors/external_task.py", line 334, in execute
    super().execute(context)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/sensors/base.py", line 257, in execute
    raise e
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/sensors/base.py", line 239, in execute
    poke_return = self.poke(context)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 77, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/sensors/external_task.py", line 241, in poke
    serialized_dttm_filter = ",".join(dt.isoformat() for dt in dttm_filter)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/sensors/external_task.py", line 241, in <genexpr>
    serialized_dttm_filter = ",".join(dt.isoformat() for dt in dttm_filter)
AttributeError: 'NoneType' object has no attribute 'isoformat'
[2023-11-01T13:19:16.322+0700] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=etl_pipeline, task_id=wait_for_first_dag, execution_date=20231101T060000, start_date=20231101T061916, end_date=20231101T061916
[2023-11-01T13:19:16.339+0700] {standard_task_runner.py:104} ERROR - Failed to execute job 24 for task wait_for_first_dag ('NoneType' object has no attribute 'isoformat'; 255)
[2023-11-01T13:19:16.402+0700] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-01T13:19:16.446+0700] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
